package com.example.ui.strings

import androidx.compose.runtime.compositionLocalOf

enum class AppLanguage(val code: String, val displayName: String, val flag: String) {
    SPANISH("es", "Español", "🇪🇸"),
    ENGLISH("en", "English", "🇬🇧")
}

data class TranslationStrings(
    val appName: String,
    val appTagline: String,
    // Bottom Nav
    val navDashboard: String,
    val navQuotes: String,
    val navCustomers: String,
    val navProjects: String,
    val navMore: String,
    // Quick Actions
    val newQuote: String,
    val newCustomer: String,
    val newProject: String,
    val newExpense: String,
    val scanReceipt: String,
    val newTask: String,
    // Dashboard metrics
    val quotesCreated: String,
    val quotesSent: String,
    val quotesAccepted: String,
    val quotesRejected: String,
    val quotesPending: String,
    val pendingInvoices: String,
    val paymentsReceived: String,
    val monthlyExpenses: String,
    val estimatedProfit: String,
    val activeProjects: String,
    val finishedProjects: String,
    val pendingTasks: String,
    val budgetedVsSpent: String,
    val periodToday: String,
    val periodWeek: String,
    val periodMonth: String,
    val periodYear: String,
    val periodAll: String,
    // Quotes
    val quoteNumber: String,
    val customer: String,
    val project: String,
    val projectType: String,
    val date: String,
    val totalAmount: String,
    val statusDraft: String,
    val statusSent: String,
    val statusViewed: String,
    val statusAccepted: String,
    val statusRejected: String,
    val statusExpired: String,
    val createQuoteStep1: String,
    val createQuoteStep2: String,
    val createQuoteStep3: String,
    val createQuoteStep4: String,
    val selectCustomer: String,
    val createNewCustomer: String,
    val selectProjectType: String,
    val quoteItems: String,
    val addItem: String,
    val itemDescription: String,
    val itemCategory: String,
    val itemQuantity: String,
    val itemUnit: String,
    val itemPrice: String,
    val itemDiscount: String,
    val subtotal: String,
    val discount: String,
    val taxableBase: String,
    val vat: String,
    val total: String,
    val exportPdf: String,
    val sendWhatsApp: String,
    val sendEmail: String,
    val digitalSignature: String,
    val convertToInvoice: String,
    // Projects
    val projectKitchen: String,
    val projectBathroom: String,
    val projectFacade: String,
    val projectPool: String,
    val projectFullRenovation: String,
    val projectConstruction: String,
    val projectElectricity: String,
    val projectPlumbing: String,
    val projectHVAC: String,
    val projectMasonry: String,
    val projectPainting: String,
    val projectFlooring: String,
    val projectDrywall: String,
    val projectOther: String,
    val statusPlanned: String,
    val statusInPrep: String,
    val statusInProgress: String,
    val statusPaused: String,
    val statusCompleted: String,
    val statusCancelled: String,
    val tabSummary: String,
    val tabQuote: String,
    val tabExpenses: String,
    val tabInvoices: String,
    val tabPayments: String,
    val tabPhotos: String,
    val tabTasks: String,
    val tabPhases: String,
    val photoBefore: String,
    val photoDuring: String,
    val photoAfter: String,
    val addPhoto: String,
    // OCR & Invoices
    val ocrTitle: String,
    val ocrSupplier: String,
    val ocrInvoiceNumber: String,
    val ocrDetectedAmount: String,
    val ocrVatDetected: String,
    val ocrCorrect: String,
    val ocrSaveInvoice: String,
    val ocrCancel: String,
    val ocrAskAddToProject: String,
    val ocrYesAdd: String,
    // Calculators
    val calcTiles: String,
    val calcPaint: String,
    val calcCement: String,
    val calcWasteMargin: String,
    val calcResultBoxes: String,
    val calcResultLiters: String,
    val calcResultBags: String,
    // Auth & Demo
    val loginTitle: String,
    val loginSubtitle: String,
    val loginButton: String,
    val demoButton: String,
    val demoTitle: String,
    val demoSubtitle: String,
    val demoRemainingTime: String,
    val demoSessionEnded: String,
    val demoRequestCode: String,
    val demoEnterCode: String,
    val demoCodeHelp: String,
    val logout: String,
    // More menu
    val menuInvoices: String,
    val menuExpenses: String,
    val menuPayments: String,
    val menuTasks: String,
    val menuTemplates: String,
    val menuPriceList: String,
    val menuCalculator: String,
    val menuSettings: String,
    val menuUsers: String,
    val menuLanguage: String,
    val menuDemoCode: String,
    // General
    val save: String,
    val cancel: String,
    val delete: String,
    val edit: String,
    val searchPlaceholder: String,
    val name: String,
    val phone: String,
    val email: String,
    val address: String,
    val notes: String,
    val successSaved: String,
    val confirmation: String
)

val SpanishStrings = TranslationStrings(
    appName = "ReformasPro",
    appTagline = "Gestiona presupuestos, obras, clientes y facturas desde un solo lugar.",
    navDashboard = "Dashboard",
    navQuotes = "Presupuestos",
    navCustomers = "Clientes",
    navProjects = "Proyectos",
    navMore = "Más",
    newQuote = "+ Nuevo presupuesto",
    newCustomer = "+ Nuevo cliente",
    newProject = "+ Nuevo proyecto",
    newExpense = "+ Nuevo gasto",
    scanReceipt = "📷 Fotografiar factura",
    newTask = "+ Nueva tarea",
    quotesCreated = "Presupuestos creados",
    quotesSent = "Enviados",
    quotesAccepted = "Aceptados",
    quotesRejected = "Rechazados",
    quotesPending = "Pendientes",
    pendingInvoices = "Facturas ptes. cobro",
    paymentsReceived = "Pagos recibidos",
    monthlyExpenses = "Gastos del mes",
    estimatedProfit = "Beneficio estimado",
    activeProjects = "Obras activas",
    finishedProjects = "Obras terminadas",
    pendingTasks = "Tareas pendientes",
    budgetedVsSpent = "Presupuestado vs Gastado",
    periodToday = "Hoy",
    periodWeek = "Esta semana",
    periodMonth = "Este mes",
    periodYear = "Este año",
    periodAll = "Todo",
    quoteNumber = "Nº Presupuesto",
    customer = "Cliente",
    project = "Proyecto",
    projectType = "Tipo de obra",
    date = "Fecha",
    totalAmount = "Importe Total",
    statusDraft = "Borrador",
    statusSent = "Enviado",
    statusViewed = "Visto",
    statusAccepted = "Aceptado",
    statusRejected = "Rechazado",
    statusExpired = "Caducado",
    createQuoteStep1 = "1. Cliente",
    createQuoteStep2 = "2. Tipo de Obra",
    createQuoteStep3 = "3. Partidas",
    createQuoteStep4 = "4. Resumen y Cierre",
    selectCustomer = "Seleccionar cliente existente",
    createNewCustomer = "Crear nuevo cliente",
    selectProjectType = "Seleccionar tipo de obra",
    quoteItems = "Partidas presupuestarias",
    addItem = "+ Añadir partida",
    itemDescription = "Descripción de la partida",
    itemCategory = "Categoría",
    itemQuantity = "Cantidad",
    itemUnit = "Unidad",
    itemPrice = "Precio unitario (€)",
    itemDiscount = "Descuento (%)",
    subtotal = "Subtotal",
    discount = "Descuento",
    taxableBase = "Base imponible",
    vat = "I.V.A.",
    total = "Total Presupuesto",
    exportPdf = "Exportar a PDF",
    sendWhatsApp = "Enviar por WhatsApp",
    sendEmail = "Enviar por Email",
    digitalSignature = "Firma digital del cliente",
    convertToInvoice = "Convertir en factura",
    projectKitchen = "Cocina",
    projectBathroom = "Baño",
    projectFacade = "Fachada",
    projectPool = "Piscina",
    projectFullRenovation = "Reforma integral",
    projectConstruction = "Construcción",
    projectElectricity = "Electricidad",
    projectPlumbing = "Fontanería",
    projectHVAC = "Aire acondicionado",
    projectMasonry = "Albañilería",
    projectPainting = "Pintura",
    projectFlooring = "Suelos",
    projectDrywall = "Pladur",
    projectOther = "Otro",
    statusPlanned = "Planificado",
    statusInPrep = "En preparación",
    statusInProgress = "En curso",
    statusPaused = "Pausado",
    statusCompleted = "Finalizado",
    statusCancelled = "Cancelado",
    tabSummary = "Resumen",
    tabQuote = "Presupuesto",
    tabExpenses = "Gastos",
    tabInvoices = "Facturas",
    tabPayments = "Pagos",
    tabPhotos = "Fotos",
    tabTasks = "Tareas",
    tabPhases = "Fases",
    photoBefore = "Antes",
    photoDuring = "Durante",
    photoAfter = "Después",
    addPhoto = "+ Subir fotografía",
    ocrTitle = "Escanear Factura / Recibo con Foto",
    ocrSupplier = "Proveedor detectado",
    ocrInvoiceNumber = "Nº Factura / Ticket",
    ocrDetectedAmount = "Importe total (€)",
    ocrVatDetected = "IVA (%)",
    ocrCorrect = "Corregir datos",
    ocrSaveInvoice = "Guardar factura",
    ocrCancel = "Cancelar",
    ocrAskAddToProject = "¿Quieres añadir este gasto al proyecto/presupuesto actual?",
    ocrYesAdd = "Sí, añadir importe",
    calcTiles = "Calculadora de Azulejos / Suelos",
    calcPaint = "Calculadora de Pintura",
    calcCement = "Calculadora de Cemento / Mortero",
    calcWasteMargin = "% Desperdicio / Cortes",
    calcResultBoxes = "Cajas aproximadas necesarias",
    calcResultLiters = "Litros aproximados de pintura",
    calcResultBags = "Sacos estimados necesarios",
    loginTitle = "Acceso a ReformasPro",
    loginSubtitle = "Software profesional para constructores y reformistas",
    loginButton = "Iniciar sesión",
    demoButton = "Probar Demostración (30 min)",
    demoTitle = "Prueba la aplicación",
    demoSubtitle = "Introduce tu teléfono o email para obtener acceso temporal",
    demoRemainingTime = "Tiempo restante demo",
    demoSessionEnded = "La sesión de demostración ha finalizado.",
    demoRequestCode = "Solicitar código de prueba",
    demoEnterCode = "Introduce tu código",
    demoCodeHelp = "Usa el código generado o 'DEMO2026' para probar sin esperas.",
    logout = "Cerrar sesión",
    menuInvoices = "Facturas",
    menuExpenses = "Gastos",
    menuPayments = "Pagos",
    menuTasks = "Tareas",
    menuTemplates = "Plantillas de Presupuesto",
    menuPriceList = "Biblioteca de Precios",
    menuCalculator = "Calculadoras de Materiales",
    menuSettings = "Configuración de Empresa",
    menuUsers = "Gestión de Usuarios",
    menuLanguage = "Idioma / Language",
    menuDemoCode = "Generador Código Demo",
    save = "Guardar",
    cancel = "Cancelar",
    delete = "Eliminar",
    edit = "Editar",
    searchPlaceholder = "Buscar cliente, obra, presupuesto...",
    name = "Nombre",
    phone = "Teléfono",
    email = "Correo electrónico",
    address = "Dirección",
    notes = "Notas",
    successSaved = "Guardado correctamente",
    confirmation = "Confirmar acción"
)

val EnglishStrings = TranslationStrings(
    appName = "ReformasPro",
    appTagline = "Manage quotes, job sites, clients and invoices all from one place.",
    navDashboard = "Dashboard",
    navQuotes = "Quotes",
    navCustomers = "Clients",
    navProjects = "Projects",
    navMore = "More",
    newQuote = "+ New Quote",
    newCustomer = "+ New Client",
    newProject = "+ New Project",
    newExpense = "+ New Expense",
    scanReceipt = "📷 Scan Receipt",
    newTask = "+ New Task",
    quotesCreated = "Quotes Created",
    quotesSent = "Sent",
    quotesAccepted = "Accepted",
    quotesRejected = "Rejected",
    quotesPending = "Pending",
    pendingInvoices = "Pending Invoices",
    paymentsReceived = "Payments Received",
    monthlyExpenses = "Monthly Expenses",
    estimatedProfit = "Estimated Profit",
    activeProjects = "Active Sites",
    finishedProjects = "Finished Projects",
    pendingTasks = "Pending Tasks",
    budgetedVsSpent = "Budget vs Actual Spent",
    periodToday = "Today",
    periodWeek = "This Week",
    periodMonth = "This Month",
    periodYear = "This Year",
    periodAll = "All Time",
    quoteNumber = "Quote #",
    customer = "Client",
    project = "Project",
    projectType = "Work Type",
    date = "Date",
    totalAmount = "Total Amount",
    statusDraft = "Draft",
    statusSent = "Sent",
    statusViewed = "Viewed",
    statusAccepted = "Accepted",
    statusRejected = "Rejected",
    statusExpired = "Expired",
    createQuoteStep1 = "1. Client",
    createQuoteStep2 = "2. Project Type",
    createQuoteStep3 = "3. Items",
    createQuoteStep4 = "4. Summary & Terms",
    selectCustomer = "Select existing client",
    createNewCustomer = "Create new client",
    selectProjectType = "Select work type",
    quoteItems = "Line Items",
    addItem = "+ Add Item",
    itemDescription = "Item Description",
    itemCategory = "Category",
    itemQuantity = "Quantity",
    itemUnit = "Unit",
    itemPrice = "Unit Price ($/€)",
    itemDiscount = "Discount (%)",
    subtotal = "Subtotal",
    discount = "Discount",
    taxableBase = "Taxable Base",
    vat = "VAT / Tax",
    total = "Total Quote",
    exportPdf = "Export to PDF",
    sendWhatsApp = "Share via WhatsApp",
    sendEmail = "Send via Email",
    digitalSignature = "Client Digital Signature",
    convertToInvoice = "Convert to Invoice",
    projectKitchen = "Kitchen",
    projectBathroom = "Bathroom",
    projectFacade = "Facade",
    projectPool = "Pool",
    projectFullRenovation = "Full Renovation",
    projectConstruction = "Construction",
    projectElectricity = "Electrical",
    projectPlumbing = "Plumbing",
    projectHVAC = "HVAC / A/C",
    projectMasonry = "Masonry",
    projectPainting = "Painting",
    projectFlooring = "Flooring",
    projectDrywall = "Drywall",
    projectOther = "Other",
    statusPlanned = "Planned",
    statusInPrep = "In Preparation",
    statusInProgress = "In Progress",
    statusPaused = "Paused",
    statusCompleted = "Completed",
    statusCancelled = "Cancelled",
    tabSummary = "Summary",
    tabQuote = "Quote",
    tabExpenses = "Expenses",
    tabInvoices = "Invoices",
    tabPayments = "Payments",
    tabPhotos = "Photos",
    tabTasks = "Tasks",
    tabPhases = "Phases",
    photoBefore = "Before",
    photoDuring = "During",
    photoAfter = "After",
    addPhoto = "+ Upload Photo",
    ocrTitle = "Scan Invoice / Receipt with Camera",
    ocrSupplier = "Detected Supplier",
    ocrInvoiceNumber = "Invoice / Ticket #",
    ocrDetectedAmount = "Total Amount",
    ocrVatDetected = "Tax / VAT (%)",
    ocrCorrect = "Edit Fields",
    ocrSaveInvoice = "Save Expense",
    ocrCancel = "Cancel",
    ocrAskAddToProject = "Do you want to add this expense to the current project/quote?",
    ocrYesAdd = "Yes, add expense",
    calcTiles = "Tiles & Flooring Calculator",
    calcPaint = "Paint Calculator",
    calcCement = "Cement & Mortar Calculator",
    calcWasteMargin = "% Waste / Offcuts",
    calcResultBoxes = "Estimated Boxes Needed",
    calcResultLiters = "Estimated Paint Liters",
    calcResultBags = "Estimated Bags Needed",
    loginTitle = "ReformasPro Login",
    loginSubtitle = "Professional software for contractors & builders",
    loginButton = "Log In",
    demoButton = "Try Demo Mode (30 min)",
    demoTitle = "Try the Application",
    demoSubtitle = "Enter your phone or email to get a single-use demo code",
    demoRemainingTime = "Demo time left",
    demoSessionEnded = "Your demo session has expired.",
    demoRequestCode = "Request Test Code",
    demoEnterCode = "Enter your code",
    demoCodeHelp = "Use your generated code or 'DEMO2026' for instant trial.",
    logout = "Sign Out",
    menuInvoices = "Invoices",
    menuExpenses = "Expenses",
    menuPayments = "Payments",
    menuTasks = "Tasks",
    menuTemplates = "Quote Templates",
    menuPriceList = "Price Database",
    menuCalculator = "Material Calculators",
    menuSettings = "Company Settings",
    menuUsers = "User Management",
    menuLanguage = "Language / Idioma",
    menuDemoCode = "Demo Code Generator",
    save = "Save",
    cancel = "Cancel",
    delete = "Delete",
    edit = "Edit",
    searchPlaceholder = "Search client, job, quote...",
    name = "Name",
    phone = "Phone",
    email = "Email",
    address = "Address",
    notes = "Notes",
    successSaved = "Saved successfully",
    confirmation = "Confirm action"
)

val LocalStrings = compositionLocalOf { SpanishStrings }
val LocalLanguage = compositionLocalOf { AppLanguage.SPANISH }
